version: "3.8"
services:
  nginx:
    container_name: nginx
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "8000:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./backend:/var/www/html/backend
  php:
    container_name: php
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/html/backend
    working_dir: /var/www/html/backend

  react:
    build: ./docker/react
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/var/www/html/frontend
    working_dir: /var/www/html/frontend

  react-run:
    image: node:latest
    volumes:
      - ./frontend:/var/www/html/frontend
    working_dir: /var/www/html/frontend
    command: sh -c "npm install && npm run build && HTTPS=true npm start"

  composer:
    container_name: composer
    image: composer/composer
    volumes:
      - ./backend:/var/www/html/backend
    working_dir: /var/www/html/backend
    command: install

  queue-sync-news:
    build: ./docker/php
    container_name: SYNC_INTEGRATION_QUEUE
    volumes:
      - ./backend:/var/www/html/backend
    working_dir: /var/www/html/backend
    command: sh -c "php artisan queue:work --queue='SYNC_INTEGRATIONS' --daemon"

  queue-save-news:
    build: ./docker/php
    container_name: SAVE_NEWS_QUEUE
    volumes:
      - ./backend:/var/www/html/backend
    working_dir: /var/www/html/backend
    command: sh -c "php artisan queue:work --queue='SAVE_NEWS' --daemon"

  mysql:
    image: mysql:8.0.27
    container_name: db
    environment:
      MYSQL_DATABASE: news_feeds
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    cap_add:
      - SYS_NICE
    ports:
      - "3307:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  
    volumes:
      - ./database/mysql:/var/lib/mysql