FROM node:latest

# WORKDIR /app

# 
# COPY package.json /app/package.json
# COPY package-lock.json /app/package-lock.json

# WORKDIR /app
# COPY . .
# ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache
# RUN ls
# RUN npm install
# RUN npm run build
# ENTRYPOINT npm start